name: cattle_breed_app
description: AI Powered Cattle Breed Recognition App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 🌐 Internet API
  http: ^1.2.1

  # 🌍 Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # 🧠 AI Model (FIXED VERSION)
  tflite_flutter: ^0.11.0
  image: ^4.1.7

  # 📸 Image Picker
  image_picker: ^1.0.7

  # 💾 Local Storage (history)
  shared_preferences: ^2.2.2

  # ☁️ Supabase (login)
  supabase_flutter: ^2.3.4

  # 🧠 State Management (FIXED ERROR)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/model/
    - assets/labels/